export default {
  "tdlyxz_monographicAnalysis":{
    "type":"monographicAnalysis",
    "typeName":"审批应用服务",
    "dialogTitle":"土地利用现状",
    "xmlType":"DLTJKC",
    "name":"土地利用现状",
    "showList":['summary','fields','year']
  },
  "tdlyztgh_monographicAnalysis":{
    "type":"monographicAnalysis",
    "typeName":"审批应用服务",
    "dialogTitle":"土地利用总体规划",
    "xmlType":"CCD",
    "name":"土地利用总体规划",
    "showList":['summary','fields']
  },
  "yjxjbnt_monographicAnalysis":{
    "type":"monographicAnalysis",
    "typeName":"审批应用服务",
    "dialogTitle":"永久性基本农田",
    "xmlType":"CCD",
    "name":"永久性基本农田",
    "showList":['summary','fields']
  },
  "sthx_monographicAnalysis":{
    "type":"monographicAnalysis",
    "typeName":"审批应用服务",
    "dialogTitle":"生态红线",
    "xmlType":"CCD",
    "name":"生态红线",
    "showList":['summary','fields']
  },
  "lnpdfw_monographicAnalysis":{
    "type":"monographicAnalysis",
    "typeName":"审批应用服务",
    "dialogTitle":"历年批地范围",
    "xmlType":"CCD",
    "name":"历年批地范围",
    "showList":['summary','fields']
  },
  "wpjwftb_monographicAnalysis":{
    "type":"monographicAnalysis",
    "typeName":"审批应用服务",
    "dialogTitle":"卫片及违法图斑",
    "xmlType":"CCD",
    "name":"卫片及违法图斑",
    "showList":['summary','fields']
  },
  "fykczydc_monographicAnalysis":{
    "type":"monographicAnalysis",
    "typeName":"审批应用服务",
    "dialogTitle":"压覆矿产资源调查",
    "xmlType":"CCD",
    "name":"压覆矿产资源调查",
    "showList":['summary','fields']
  },
  "ydgy_monographicAnalysis":{
    "type":"monographicAnalysis",
    "typeName":"审批应用服务",
    "dialogTitle":"用地供应",
    "xmlType":"CCD",
    "name":"用地供应",
    "showList":['summary','fields']
  },
  "wfydclqkfx_monographicAnalysis":{
    "type":"monographicAnalysis",
    "typeName":"审批应用服务",
    "dialogTitle":"违法用地处理情况分析",
    "xmlType":"CCD",
    "name":"违法用地处理情况分析",
    "showList":['summary','fields']
  },
  "tdlyxz_bigDataAnalysis":{
    "type":"bigDataAnalysis",
    "typeName":"大数据",
    "dialogTitle":"土地利用现状",
    "xmlType":"DLTJKC",
    "name":"土地利用现状",
    "showList":['fields','year']
  },
  "tdlyztgh_bigDataAnalysis":{
    "type":"bigDataAnalysis",
    "typeName":"大数据",
    "dialogTitle":"土地利用总体规划",
    "xmlType":"CCD",
    "name":"土地利用总体规划",
    "showList":['fields']
  },
  "yjxjbnt_bigDataAnalysis":{
    "type":"bigDataAnalysis",
    "typeName":"大数据",
    "dialogTitle":"永久性基本农田",
    "xmlType":"CCD",
    "name":"永久性基本农田",
    "showList":['fields']
  },
  "sthx_bigDataAnalysis":{
    "type":"bigDataAnalysis",
    "typeName":"大数据",
    "dialogTitle":"生态红线",
    "xmlType":"CCD",
    "name":"生态红线",
    "showList":['fields']
  },
  "lnpdfw_bigDataAnalysis":{
    "type":"bigDataAnalysis",
    "typeName":"大数据",
    "dialogTitle":"历年批地范围",
    "xmlType":"CCD",
    "name":"历年批地范围",
    "showList":['fields']
  },
  "wpjwftb_bigDataAnalysis":{
    "type":"bigDataAnalysis",
    "typeName":"大数据",
    "dialogTitle":"卫片及违法图斑",
    "xmlType":"CCD",
    "name":"卫片及违法图斑",
    "showList":['fields']
  },
  "fykczydc_bigDataAnalysis":{
    "type":"bigDataAnalysis",
    "typeName":"大数据",
    "dialogTitle":"压覆矿产资源调查",
    "xmlType":"CCD",
    "name":"压覆矿产资源调查",
    "showList":['fields']
  },
  "ydgy_bigDataAnalysis":{
    "type":"bigDataAnalysis",
    "typeName":"大数据",
    "dialogTitle":"用地供应",
    "xmlType":"CCD",
    "name":"用地供应",
    "showList":['fields']
  },
  "wfydclqkfx_bigDataAnalysis":{
    "type":"bigDataAnalysis",
    "typeName":"大数据",
    "dialogTitle":"违法用地处理情况分析",
    "xmlType":"CCD",
    "name":"违法用地处理情况分析",
    "showList":['fields']
  }
}